version: '2'

services:
  http:
    image: nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./http/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend

  application:
    build:
      context: ./application
    restart: unless-stopped
    depends_on:
      - http
    expose:
      - '8080'
    networks:
      backend:
        aliases:
          - application
networks:
  backend: {}
